apiVersion: v1
kind: Pod
metadata:
   name: pod1
   labels:
     run: web
     point: one
spec:
   containers:
     - image: nginx
       name: web
       args:
        - /bin/sh
        - -c
        - touch hello; echo $HOST_NAME > hello; cat hello; sleep 10
       env:
        - name: HOST_NAME
          valueFrom:
            configMapKeyRef:
               name: web-config
               key: HOST_NAME
